# Generated by Django 5.2 on 2025-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=40)),
            ],
        ),
    ]
