# Generated by Django 5.2 on 2025-05-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'db_table': 'ESTADO_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_disponible', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'INVENTARIO',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id_medpago', models.AutoField(primary_key=True, serialize=False)),
                ('nom_medpago', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'MEDIO_DE_PAGO',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'REGION',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'ROL_USER',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id_tipo_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_comprobante', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobante',
                'db_table': 'TIPO_COMPROBANTE',
            },
        ),
        migrations.CreateModel(
            name='TipoDespacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('nom_despacho', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Despacho',
                'verbose_name_plural': 'Tipos de Despacho',
                'db_table': 'TIPO_DESPACHO',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=60)),
                ('marca_prod', models.CharField(max_length=20)),
                ('codigo_fabricante', models.IntegerField()),
                ('precio_prod', models.IntegerField()),
                ('estado_prod', models.BooleanField()),
                ('foto_prod', models.BinaryField(blank=True, null=True)),
                ('inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.inventario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
                'unique_together': {('nom_prod', 'marca_prod')},
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=60)),
                ('region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'db_table': 'COMUNA',
                'unique_together': {('nom_comuna', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_sucursal', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
            options={
                'db_table': 'SUCURSAL',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sucursal'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_user', models.CharField(max_length=60)),
                ('apellido_user', models.CharField(max_length=60)),
                ('rut_user', models.IntegerField(unique=True)),
                ('dv_user', models.IntegerField()),
                ('celular_user', models.IntegerField()),
                ('pass_user', models.CharField(max_length=12)),
                ('email_user', models.EmailField(max_length=100, unique=True)),
                ('direccion_user', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_user', models.BooleanField()),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='api.comuna')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='api.role')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('total_pedido', models.IntegerField()),
                ('confirmacion_entrega', models.BooleanField(blank=True, db_column='confirmación_entrega', null=True)),
                ('direc_desp', models.CharField(blank=True, max_length=100, null=True)),
                ('id_comuna_dep', models.IntegerField(blank=True, null=True)),
                ('id_region_desp', models.IntegerField(blank=True, null=True)),
                ('rut_factura', models.CharField(blank=True, max_length=9, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadopedido')),
                ('sucursal', models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sucursal')),
                ('tipo_comprobante', models.ForeignKey(db_column='id_tipo_comprobante', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipocomprobante')),
                ('tipo_despacho', models.ForeignKey(db_column='id_despacho', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodespacho')),
                ('usuario', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notifi', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_notifi', models.CharField(max_length=20)),
                ('contenido_notifi', models.CharField(max_length=250)),
                ('fecha_notifi', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carrito', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'CARRITO',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pago', models.BooleanField()),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pago', models.IntegerField()),
                ('medio_pago', models.ForeignKey(db_column='id_medpago', on_delete=django.db.models.deletion.DO_NOTHING, to='api.mediodepago')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='api.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'PAGO',
                'unique_together': {('medio_pago', 'pedido')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='api.pedido')),
                ('producto', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'DETALLE_PEDIDO',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.DO_NOTHING, to='api.carrito')),
                ('producto', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Carrito',
                'verbose_name_plural': 'Detalles de Carrito',
                'db_table': 'DETALLE_CARRITO',
                'unique_together': {('producto', 'carrito')},
            },
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('direccion_sucursal', 'comuna'), name='unique_direccion_comuna'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('id_inventario', 'sucursal')},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('nombre_user', 'apellido_user', 'email_user')},
        ),
    ]
