# Generated by Django 5.2 on 2025-05-03 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'REGION',
            },
        ),
        migrations.AlterModelTable(
            name='role',
            table='ROL_USER',
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=60)),
                ('region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'db_table': 'COMUNA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_user', models.CharField(max_length=60)),
                ('apellido_user', models.CharField(max_length=60)),
                ('rut_user', models.IntegerField(unique=True)),
                ('dv_user', models.IntegerField()),
                ('celular_user', models.IntegerField()),
                ('pass_user', models.CharField(max_length=12)),
                ('email_user', models.EmailField(max_length=100, unique=True)),
                ('direccion_user', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_user', models.BooleanField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.comuna')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.role')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
    ]
