# Generated by Django 5.2 on 2025-05-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_region_alter_role_table_comuna_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='api.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='api.role'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.IntegerField(unique=True)),
                ('direccion_sucursal', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
            options={
                'unique_together': {('id_sucursal', 'comuna')},
            },
        ),
    ]
