# Generated by Django 5.2 on 2025-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_comuna_alter_usuario_id_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('id_sucursal', 'comuna'), name='unique_sucursal_comuna'),
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='id',
        ),
    ]
